# Generated by Django 2.0.3 on 2018-04-03 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_dinnerplatter_pasta_regularpizza_salad_sicilianpizza_sub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dinnerplatter',
            name='size',
            field=models.CharField(choices=[('Large', 'Large'), ('Small', 'Small')], default='Small', max_length=5),
        ),
        migrations.AlterField(
            model_name='regularpizza',
            name='size',
            field=models.CharField(choices=[('Large', 'Large'), ('Small', 'Small')], default='Small', max_length=5),
        ),
        migrations.AlterField(
            model_name='sicilianpizza',
            name='size',
            field=models.CharField(choices=[('Large', 'Large'), ('Small', 'Small')], default='Small', max_length=5),
        ),
        migrations.AlterField(
            model_name='sub',
            name='size',
            field=models.CharField(choices=[('Large', 'Large'), ('Small', 'Small')], default='Small', max_length=5),
        ),
    ]
