# Generated by Django 2.0.3 on 2018-04-06 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20180403_2240'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Regular', 'Regular'), ('Sicilian', 'Sicilian')], default='Regular', max_length=8)),
                ('size', models.CharField(choices=[('Large', 'Large'), ('Small', 'Small')], default='Small', max_length=5)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.DeleteModel(
            name='RegularPizza',
        ),
        migrations.DeleteModel(
            name='SicilianPizza',
        ),
    ]
