# Generated by Django 2.0.3 on 2018-04-06 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20180406_2354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='name',
        ),
    ]
