# Generated by Django 2.0.3 on 2018-04-07 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_pizza_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='type',
            new_name='pizza_type',
        ),
        migrations.AddField(
            model_name='pizza',
            name='name',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
    ]
