# Generated by Django 2.0.3 on 2018-04-09 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20180407_0000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('entree_type', models.CharField(choices=[('Regular', 'Regular Pizza'), ('Sicilian', 'Sicilian Pizza'), ('Sub', 'Sub'), ('Pasta', 'Pasta'), ('Salad', 'Salad'), ('Dinner Platter', 'Dinner Platter')], default='Regular', max_length=8)),
                ('size', models.CharField(choices=[('Large', 'Large'), ('Small', 'Small'), ('None', 'None')], default='None', max_length=5)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.DeleteModel(
            name='DinnerPlatter',
        ),
        migrations.DeleteModel(
            name='Pasta',
        ),
        migrations.DeleteModel(
            name='Pizza',
        ),
        migrations.DeleteModel(
            name='Salad',
        ),
        migrations.DeleteModel(
            name='Sub',
        ),
    ]
