# Generated by Django 2.0.3 on 2018-04-10 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20180410_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entree',
            name='entree_type',
            field=models.CharField(choices=[('Regular Pizza', 'Regular Pizza'), ('Sicilian Pizza', 'Sicilian Pizza'), ('Sub', 'Sub'), ('Pasta', 'Pasta'), ('Salad', 'Salad'), ('Dinner Platter', 'Dinner Platter')], default='Regular Pizza', max_length=14),
        ),
    ]
