# Generated by Django 2.0.3 on 2018-04-10 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_customerorder_food_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealsInOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Entree')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.CustomerOrder')),
            ],
        ),
        migrations.AddField(
            model_name='customerorder',
            name='entree_included',
            field=models.ManyToManyField(through='orders.MealsInOrder', to='orders.Entree'),
        ),
    ]
