# Generated by Django 2.0.3 on 2018-04-10 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_auto_20180410_2338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerorder',
            name='food_items',
        ),
    ]
