# Generated by Django 2.0.3 on 2018-04-14 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_mealsinorder_toppings'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='order_completed',
            field=models.BooleanField(default=False),
        ),
    ]
