# Generated by Django 2.0.3 on 2018-04-14 18:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_customerorder_order_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
