# Generated by Django 2.0.3 on 2018-04-14 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_customerorder_submitted_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='SteakCheeseTopping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
