# Generated by Django 2.0.3 on 2018-04-14 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_steakcheesetopping'),
    ]

    operations = [
        migrations.AddField(
            model_name='steakcheesetopping',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.5, max_digits=5),
        ),
    ]
