# Generated by Django 2.0.3 on 2018-04-14 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_steakcheesetopping_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='steakcheesetopping',
            name='name',
        ),
        migrations.AddField(
            model_name='steakcheesetopping',
            name='pizzaTopping',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orders.PizzaTopping'),
            preserve_default=False,
        ),
    ]
